---
title: "Tarea_2"
author: "Stephany Pachay"
date: "2023-10-08"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##  **Tarea de la semana 3**

#  ***Niveles de Felicidad***

Para empezar, importamos los paquetes con los que vamos a trabajar

```{python}
import pandas as pd
import numpy as np
```

A continuación, vamos a usar los datos de felicidad en el link otorgado, copiamos en Raw y ese enlace lo usaremos junto con la funcion de pandas, read_csv para así poder leer el archivo, tambien agregamos la función index_col para país.

```{python}
datos_felicidad = pd.read_csv('https://raw.githubusercontent.com/cienciadedatos/datos-de-miercoles/master/datos/2019/2019-08-07/felicidad.csv', index_col="pais")
datos_felicidad
```

Una vez cargada la base de datos, se calculan las medidas de tendencia central y dispersión a nivel global para el primer y último año incluido en el set de datos, y para ello se escogió hacerlo mediante el promedio y desviación estándar.

Primero, vamos a realizar un filtro con la base de datos, para poder separar los datos dle primer año y del ultimo año.

```{python}
primer_año = datos_felicidad[datos_felicidad['anio'] == datos_felicidad['anio'].min()]
primer_año
```

```{python}
ultimo_año = datos_felicidad[datos_felicidad['anio'] == datos_felicidad['anio'].max()]
ultimo_año
```

Una vez filtrados los datos, se calcula el promedio y desviación estándar para cada año.

##### ***Primer año:***

```{python}
promedio_primer_año = primer_año['escalera_vida'].mean()
promedio_primer_año
```

```{python}
desviacion_primer_año = primer_año['escalera_vida'].std()
desviacion_primer_año
```

##### ***Último año:***

```{python}
promedio_ultimo_año = ultimo_año['escalera_vida'].mean()
promedio_ultimo_año
```

```{python}
desviacion_ultimo_año = ultimo_año['escalera_vida'].std()
desviacion_ultimo_año
```

Una vez obtenido esos valores se hizo la selección de dos paises, para al final hacer una comparación de valores a nivel mundial con los paises escogidos, en el primer año reportado y el último año reportado.

Primero hacemos la selección de paises filtrando con ayuda del método loc en pais, y lo hacemos para primer y ultimo año de cada pais.

##### ***Países primer año:***

```{python}
Australia_primer_año = primer_año.loc['Australia']
Australia_primer_año
```

```{python}
Canadá_primer_año = primer_año.loc['Canadá']
Canadá_primer_año
```

##### ***Países último año:***

```{python}
Australia_ultimo_año = ultimo_año.loc['Australia']
Australia_ultimo_año
```

```{python}
Canadá_ultimo_año = ultimo_año.loc['Canadá']
Canadá_ultimo_año
```

Filtrados los datos, se puede obtener los valores de felicidad para ambos países en el primer y último año, para ello se vuelve a hacer uso del método loc para seleccionar el valor de escalera_vida (nombre que pertenece a felicidad en los datos)

##### ***Primer año:***

```{python}
felicidad_Australia_1año = Australia_primer_año.loc['escalera_vida']
felicidad_Australia_1año
```

```{python}
felicidad_Canada_1año = Canadá_primer_año.loc['escalera_vida']
felicidad_Canada_1año
```

##### ***Último año:***

```{python}
felicidad_Austra_ultimo_año = Australia_ultimo_año.loc['escalera_vida']
felicidad_Austra_ultimo_año
```

```{python}
felicidad_Canada_ultimo_año = Canadá_ultimo_año.loc['escalera_vida']
felicidad_Canada_ultimo_año
```

Volvemos a agregar los valores del promedio y desviación estándar de felicidad del primer y último año para realizar una comparación con los valores de felicidad de primer y último año de cada país.

```{python}
promedio_primer_año; desviacion_primer_año; promedio_ultimo_año; desviacion_ultimo_año; felicidad_Australia_1año; felicidad_Canada_1año;felicidad_Austra_ultimo_año;felicidad_Canada_ultimo_año
```

Finalmente, se puede concluir que de acuerdo a los resultados obtenidos el promedio de felicidad de ambos paises en el primer año en comparación al promedio y desviación estándar a nivel mundial en el primer año es muy similar, dando una tendencia a que todos tienen el mismo nivel de felicidad o muy cercano, casi todos son igual de felices. Mientras que en el último año, se ve una diferencia en comparación a nivel mundial, pues el nivel de felicidad en ambos paises se mantiene, es decir, su reducción es minima casi no se nota, en cambio a nivel mundial ha reducido el promedio de felicidad y se ve un incremento en la desviación estándar indicando que el nivel de felicidad se está alejando del promedio, y existe una varianza en la felicidad notoria a traves del tiempo.
